services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    image: myapp_image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
       RAILS_ENV: production
       DATABASE_URL: postgres://postgres:password@db:5432/app_production
       REDIS_URL: redis://redis:6379/0
       RAILS_LOG_TO_STDOUT: "true"
       RAILS_SERVE_STATIC_FILES: "true"
       RAILS_HOST: back.topbrands-sy.com
       RAILS_PROTOCOL: https
       RAILS_ASSUME_SSL: "false"
       RAILS_FORCE_SSL: "false"
       PORT: "9007"
      # Secret key base for Rails production (generate with: openssl rand -hex 64)
       SECRET_KEY_BASE: "8e9c2d91daaa15e417fc73fd7f55289bd9f966d524a7197018b8c2aa31629431"
    ports:
      - "9007:9007"  # Map host port 9007 to container port 9007
    volumes:
      - storage:/rails/storage
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p ${PORT:-9007}"]
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f http://localhost:${PORT:-9007}/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  sidekiq:
    image: myapp_image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/app_production
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY_BASE: "8e9c2d91daaa15e417fc73fd7f55289bd9f966d524a7197018b8c2aa31629431"
    volumes:
      - storage:/rails/storage
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  storage:
